// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {analyzer} from '../models';
import {main} from '../models';
import {downloader} from '../models';

export function AddComparable(arg1:string,arg2:string):Promise<void>;

export function AddToWatchlist(arg1:string):Promise<void>;

export function AnalyzeStock(arg1:string,arg2:boolean):Promise<analyzer.AnalysisReport>;

export function AnalyzeStockWithRIM(arg1:string,arg2:boolean,arg3:string):Promise<analyzer.AnalysisReport>;

export function CheckAnalysisCache(arg1:string):Promise<main.CacheStatus>;

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function DeleteReport(arg1:string,arg2:string):Promise<void>;

export function DownloadComparableReports(arg1:string):Promise<main.DownloadResult>;

export function DownloadReport(arg1:string,arg2:string):Promise<void>;

export function DownloadReports(arg1:string,arg2:number):Promise<main.DownloadResult>;

export function ExportCurrentFinancialData(arg1:string):Promise<void>;

export function ExportHistoricalFinancialData(arg1:string,arg2:string):Promise<void>;

export function GetComparables(arg1:string):Promise<Array<string>>;

export function GetIndustryDBMeta():Promise<Record<string, any>>;

export function GetIndustryMetrics(arg1:string):Promise<analyzer.IndustryMetrics|boolean>;

export function GetModule4Status(arg1:string):Promise<boolean>;

export function GetPolicyLibraryMeta():Promise<Record<string, string>>;

export function GetReport(arg1:string,arg2:string):Promise<string>;

export function GetReportHistory(arg1:string):Promise<Array<string>>;

export function GetStockConcepts(arg1:string):Promise<downloader.StockConcepts>;

export function GetStockDataHistory(arg1:string):Promise<Array<main.HistoryMeta>>;

export function GetStockKlines(arg1:string):Promise<Array<downloader.KlineData>>;

export function GetStockProfile(arg1:string):Promise<main.StockProfile>;

export function GetStockQuote(arg1:string):Promise<downloader.StockQuote>;

export function GetWatchlist():Promise<Array<main.WatchlistItem>>;

export function GetWatchlistActivity():Promise<Array<main.WatchlistActivitySummary>>;

export function ImportFinancialReports(arg1:string):Promise<main.ImportResult>;

export function InitIndustryDatabase():Promise<void>;

export function LoadAnalysisSnapshot(arg1:string):Promise<analyzer.AnalysisReport>;

export function RefreshIndustryBaselines():Promise<Record<string, analyzer.IndustryBaseline>>;

export function RefreshStockProfile(arg1:string):Promise<main.StockProfile>;

export function ReloadPolicyLibrary():Promise<void>;

export function RemoveComparable(arg1:string,arg2:string):Promise<void>;

export function RemoveFromWatchlist(arg1:string):Promise<void>;

export function ReorderWatchlist(arg1:Array<string>):Promise<void>;

export function SaveDefaultPolicyLibrary():Promise<void>;

export function SearchStocks(arg1:string):Promise<Array<main.StockInfo>>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function UpdateIndustryDatabase():Promise<downloader.IndustryUpdateResult>;

export function UpdateModule4Only(arg1:string):Promise<analyzer.AnalysisReport>;

export function UpdatePolicyLibrary():Promise<downloader.PolicyUpdateResult>;
